databases:
  - name: eventdb
    plan: free
    databaseName: eventtracker
    user: eventtracker
services:
  - type: web
    name: eventtracker
    plan: free
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn eventsystem.wsgi --log-file -'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
